### ISSUE TITLE
[leaflet-1.0] npm install fails if jake isn't installed globally

### ISSUE THREAD

**Issue by ngoldman** [Esri/esri-leaflet-renderers#1]
Trying out the `leaflet-1.0` branch to use `spec/comparisons.html`, I noticed the following error popped up when running `npm install` on a machine where `jake` is not installed globally:

```
Error: Command failed: /bin/sh: jake: command not found

/bin/sh: jake: command not found
```

The rest of the install runs fine (this doesn't appear to halt anything), and I can view `spec/comparisons.html`, but it's a little weird so I thought I'd report it.

/cc @kneemer

**Comment by jgravois** [comment]
as for reminders, i'll add my own.  

its normal (i think) for the build to finish with an error related to failure to find `your plugin/scripts/install.js` after successfully locating the same file in the [esri-leaflet](https://github.com/Esri/esri-leaflet/blob/leaflet-1.0/scripts/install.js) and leaflet dependency folders and using them to build their source.  thx to @kneemer for taking the time to explain the whole workflow to me!

**Comment by ngoldman** [comment]
oh hey, is this resolved?

**Comment by jgravois** [comment]
i think @kneemer is planning on leaving the postinstall dependency alone until they finally tag Leaflet 1.0.  any trouble with that?

**Comment by ngoldman** [comment]
Ah ok, sorry I thought Leaflet 1.0 would have already been released by now. :horse:

**Comment by jgravois** [comment]
we all did @ngoldman.  we all did.

**Comment by ngoldman** [comment]
:skull:
