### ISSUE TITLE
more support for 'smart mapping'

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#101]
ie: asking the REST API to provide suggestions for classifications/symbology dynamically.  

@astauffer will provide more info.

**Comment by astauffer** [comment]
This is for adding the logic so when someone wants to style data the different methods are available, that are in the JS API as documented here https://developers.arcgis.com/javascript/jsapi/esri.renderers.smartmapping-amd.html

I understand we can read the renderers, but hope to see the methods to generate them within Esri leaflet.

**Comment by jgravois** [comment]
granted, its semantic at this point, but @kneemer and i agree that the work for making requests to generate renderers belongs in its own distinct plugin.  we'll take a crack at writing support for a single renderer type and see just how difficult it is, but theoretically, what comes back from `generateRenderer` should be ready to slap straight into the code here.
