### ISSUE TITLE
Renderers do not work with clusteredFeatureLayer

### ISSUE THREAD

**Issue by daniel-sabourin** [Esri/esri-leaflet-renderers#102]
When using the esri-leaflet-renderers plugin and esri-leaflet-clustered-feature-layer together. One featureLayer, one clusteredFeatureLayer, and only one shows the renderer properly

See [jsfiddle](http://jsfiddle.net/skoqkdu6/4/).

**Comment by kneemer** [comment]
@daniel-sabourin I added clustered-feature-layer support in https://github.com/Esri/esri-leaflet-renderers/releases/tag/v1.0.1 which is available at http://cdn.jsdelivr.net/leaflet.esri.renderers/1.0.1/esri-leaflet-renderers.js

It will not be supported in 2.0.0 until https://github.com/Leaflet/Leaflet.markercluster has a release for leaflet 1.0.

Please reopen if it does not address your issue.

**Comment by daniel-sabourin** [comment]
Awesome, checked it out and it's working great! Thanks!
