### ISSUE TITLE
Race condition in 2.0.0-beta.7

### ISSUE THREAD

**Issue by PatrickKing** [Esri/esri-leaflet-renderers#105]
Hi all, 

I'm seeing a race condition, where if map updates occur while a feature layer is loading, the layer accesses some variables which have not been initialized yet and crashes.

I've [reproduced the problem a gist](https://gist.github.com/PatrickKing/1185c9584cf1e521d8c7). A feature layer is loaded and unloaded at 5 second intervals, and the crash occurs when we call `map.setZoom`.

Not 100% sure this is from esri-leaflet-renderers, but the exception no longer occurs if you comment the line importing renderers in the gist.

Thanks!

Edited to add: For some context, we are using react-leaflet. React has asynchronous event systems which operate in the background, with the result that we encounter this issue reliably in our app. I didn't go hunting for obscure race conditions at random.

**Comment by kneemer** [comment]
@PatrickKing are you able to test the latest changes from master to be sure the resolution addresses the issues you are seeing?

Once you verify we can do a new release.

**Comment by PatrickKing** [comment]
I've just run master against my test gist, it looks like the issue is resolved. Thanks!

**Comment by kneemer** [comment]
@jgravois I'm occasionally seeing behavior where the renderer is not applied to all features and am wondering if it is due to this change.  I didn't see the issue before.

**Comment by jgravois** [comment]
okay, lets dig in deeper before we tag anything...

**Comment by kneemer** [comment]
Ok, I don't have steps to reproduce yet.

**Comment by kneemer** [comment]
@jgravois I saw the issue again and was logging which methods were being called.  In the normal and problem case the order of onAdd and metadata calls were the same so I'm thinking the issue is not related to this change.  I'll keep this open for now until we know for sure.
