### ISSUE TITLE
add option for individual L.esri.featureLayers to not pick up renderer defined in service

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#110]
talked to a developer yesterday who said it would be helpful if he could only invoke this plugin for *some* of the layers in his map.

seems to me like it would be easy enough to add a check for a new constructor option in `addInitHook()` and abort if `useRenderer != true`.
```js
if (this.options.useRenderer)
  // proceed
```

curious to hear other thoughts.  i think this is the first thing that gets us into territory of needing additional API doc specific to the plugin...

**Comment by kneemer** [comment]
That is pretty easy, I'll get on it.  I agree that once we start introducing flags we will need docs.

**Comment by kneemer** [comment]
@jgravois I think I'm going to use ignoreRenderer so that the default is to use the renderer when the option is not specified.
