### ISSUE TITLE
found a service this plugin seems to choke on

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#115]
why doesn't the service below draw when we try to inherit service symbology?
http://sampleserver6.arcgisonline.com/arcgis/rest/services/CommunityAddressing/MapServer/0

**Comment by kneemer** [comment]
I think this is an error with the service and its metadata.  The metadata says to render on the `status` field.
![screen shot 2016-06-10 at 2 33 32 pm](https://cloud.githubusercontent.com/assets/30075/15979418/b7d82566-2f18-11e6-82cc-5f51338245da.png)

However, the features returned from the server do not seem to have a `status` field.
![screen shot 2016-06-10 at 2 34 52 pm](https://cloud.githubusercontent.com/assets/30075/15979443/de06c2ec-2f18-11e6-9500-257e492617fc.png)

**Comment by jgravois** [comment]
good find!  i was being lazy and used [this](http://sampleserver6.arcgisonline.com/arcgis/rest/services/CommunityAddressing/MapServer?f=jsapi) to confirm it drew in the JSAPI, but thats just a dynamic map service!
