### ISSUE TITLE
remove marker tests

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#116]
i can/should get rid of the marker tests here, right?
https://github.com/Esri/esri-leaflet-renderers/tree/master/spec/Markers

**Comment by kneemer** [comment]
@jgravois, I had hoped to add a test that verified that the shapeMarkers library was loaded/working and then remove these tests but didn't get around to it.

**Comment by jgravois** [comment]
i can do that if you can sanity check the PR below :wink:

Esri/Leaflet.shapeMarkers#22

i also understand if you ever decide you need to get away from both of these repos entirely.

**Comment by kneemer** [comment]
I put these repos into the wild so I feel some sense of stewardship still towards them 😄
