### ISSUE TITLE
Inherit style option

### ISSUE THREAD

**Issue by jmfolds** [Esri/esri-leaflet-renderers#122]
L.featureLayer should inherit style option rather than override.

http://codepen.io/jmfolds/pen/WxpwOR

**Comment by jmfolds** [comment]
This may be specific to the "clickable" property.

**Comment by jgravois** [comment]
in Leaflet 1.0.0-rc.1 `clickable` is no longer a path option.  it has been replaced by [`interactive`](http://leafletjs.com/reference-1.0.0.html#path-interactive).

**Comment by jfolds** [comment]
+1 I noticed this on an app using 0.7.x so this should probably be closed, unless you are still supporting older versions.

**Comment by jgravois** [comment]
we didn't incorporate an option for developers to mixin their own options until [`2.0.3`](https://github.com/Esri/esri-leaflet-renderers/releases/tag/v2.0.1).

if Leaflet doesn't tag `1.0.0` soon and anyone desperately needs the functionality i'd be willing to consider backporting, but in general i'm trying to limit support for our `0.7.x` compatible plugins to bug fixes.

either way, thanks for reporting.  i'm sure the info will be helpful to someone down the road.
