### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [Esri/esri-leaflet-renderers#130]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I don't know which files should be added.
Could you help me?
Thanks!
https://github.com/cdnjs/cdnjs/issues/8862

**Comment by jgravois** [comment]
everything in here:
https://github.com/Esri/esri-leaflet-renderers/tree/v2.0.4/dist

thx! 😉

**Comment by x09326** [comment]
@jgravois 
Is the debug file also needed?

**Comment by jgravois** [comment]
ideally [yes](https://github.com/jsdelivr/jsdelivr/pull/10203#issuecomment-191484460).
