### ISSUE TITLE
add support for text symbols

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-renderers#131]
I've successfully integrated esri-leaflet-renders, as a result instead of the 'common' marker I see the correct symbol described in the drawing info. However, I can't see the label above the symbol.
Are labeling info supported ? 

The one I'm using is defined as:

```
Labeling Info:
    Label Placement: esriServerPointLabelPlacementAboveRight 
    Label Expression: [IDENTIFICATIVO] 
    Use Coded Values: false 
    Symbol:
        Color: [255, 0, 0, 255] 
        Background Color: N/A 
        Outline Color: N/A 
        Vertical Alignment: bottom 
        Horizontal Alignment: center 
        Right to Left: false 
        Angle: 0 
        XOffset: 0
        YOffset: 0
        Size: 9 
        Font Family: Arial 
        Font Style: normal 
        Font Weight: bold 
        Font Decoration: none 
        Min. Scale: 15000.0 
        Max. Scale: 0.0 
```

**Comment by jgravois** [comment]
from https://github.com/Esri/esri-leaflet-renderers/blob/master/README.md#limitations

> Text symbols are not supported.

**Comment by mepdr** [comment]
I'd use text symbols for both Points and LineString, is there any plan to support them?

**Comment by pmacMaps** [comment]
@mepdr Not sure what your end goal is, but if I want to have labels for my layers, I will do one of two things.  Not sure if they would work for you:

1. Publish layer as a map service with labels enabled.
2. Publish a service without labels (feature or map service), and then publish a map service with the labels, but the symbols turned off.  

When using a map service, the labels will redraw dynamically as the map extent changes.

**Comment by jgravois** [comment]
@mepdr no one is working on introducing support for text symbols at the moment, but pull requests are welcome.

@pmacMaps thanks for outlining a few relevant alternative workflows.  they're both totally relevant.

**Comment by mepdr** [comment]
Thanks for answers.
@pmacMaps I've a layer exposed as MapServer but I'm unable to use tiles, not sure why. The arcgis javascript example works though.
@jgravois how difficult will be to introduce such support? Would you share few advises where/how to start

**Comment by jgravois** [comment]
@mepdr even if a map service has not been cached and no tiles exist to be served out it is still possible to draw the associated layers in esri-leaflet using `L.esri.dynamicMapLayer`.  this is a technique which will allow you to 'turn on' labels for the individual layer without writing any code of your own.

example:
http://jsbin.com/yoluvi/1/edit?html,output
