### ISSUE TITLE
setWhere callback is not called

### ISSUE THREAD

**Issue by mepdr** [Esri/esri-leaflet-renderers#132]
Changing the where condition on a newly created layer doesn't let the callback to be executed.
see http://jsbin.com/qonevevojo/edit?html,console,output
While the callback is correctly executed if the setWhere is executed after a few seconds.
Looking at the code, this seems to happen because `oldOnAdd` (https://github.com/Esri/esri-leaflet-renderers/blob/master/src/FeatureLayerHook.js#L27) is called only when metadata returns. By doing this in FeatureManager setWhere `this._activeCells`  (https://github.com/Esri/esri-leaflet/blob/2cf1b3b375f38a174b9b48544dfbffd2320031e4/src/Layers/FeatureLayer/FeatureManager.js#L242)  is undefined when setWhere is called too soon (before metadata has returned).

**Comment by mepdr** [comment]
Is there any update or workaround on that?

**Comment by jgravois** [comment]
if there was an update, i would have posted it here. :smile:

**Comment by jwasilgeo** [comment]
@mepdr because Esri/esri-leaflet#875 was fixed and closed I am hoping this is no longer an issue. Can you verify please?
