### ISSUE TITLE
featureLayer throws 'this.options.userDefinedStyle is not a function' intermittently

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#133]
started sometime after `2.0.2` was tagged

more info in Esri/esri-leaflet#874

**Comment by jgravois** [comment]
a user reported this again today.

**Comment by HarelM** [comment]
Reproduction:
http://jsbin.com/batofehiyo/edit?html,output
Seems like setStyle is not behaving nice :-/

**Comment by jgravois** [comment]
thanks for isolating a repro case. until the issue is resolved, try this:

```js
// pass a function instead of PathOptions
parks.setStyle(function(feature){
  return { fillOpacity: 0.1 };
});
```

**Comment by HarelM** [comment]
Thanks again! but don't worry. 
I have a workaround that exists in the jsbin by using the giving the `style` property a function:
```
var parks = L.esri.featureLayer({
        url: "https://ags.moin.gov.il/arcgis/rest/services/PlanningPublic/tama35_hanchayot_svivatiot/MapServer/14",
        style: function () {
          return { fillOpacity: 0.1 };
        }
      }).addTo(map);
```

**Comment by jgravois** [comment]
PRs welcome, I don't have plans to work on this one though.

**Comment by akmware** [comment]
We resolved this by stated the "ignoreRenderer" option to true or false when setting up L.esri.FeatureLayer. this was changed from renderer 2.0.2 onwards
