### ISSUE TITLE
picture marker symbols in custom panes don't draw in drupal (and other CMSs)

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-renderers#138]
I've found a weird quirk while upgrading some embedded maps on my organization's website.  I'm upgrading from 0.7.x to 1.0.x.  The features appear in the DOM (attached image) with an outline of the features, but did not appear on the map.  When I removed the Esri Leaflet Renderers plugin, the features appeared on the map.  

Another strange thing is that a polygon layer drew in either case, but a point feature class did not.  I tested with both a map service (feature layer) on our ArcGIS Server and an ArcGIS Online Hosted Feature Service.  The issue occurred in both instances.  

Not sure if it's an issue with the plugins or with my organization's CMS [CivicPlus](https://www.civicplus.com/).  I also have some full-page apps on our [subdomain](https://gis.ccpa.net/maps/countysites/) that didn't have this issue.  I noticed the issue was in both Chrome 58.0.3029.96 and IE 11.0.9600.18638.

**Details/links below:**

Working version: https://www.ccpa.net/3938/County-Sites-Map
- Leaflet v. 0.7.7
- Esri Leaflet v.  1.0.2
- Esri Leaflet Renderers v 1.0.1

Upgraded Version without Esri Leaflet Renderers: https://www.ccpa.net/4464/Leaflet-County-Sites-Upgrade-Testing
- Leaflet v. 1.0.3
- Esri Leaflet v. 2.0.7

Upgraded Version with Esri Leaflet Renderers: https://www.ccpa.net/4466/Leaflet-Senior-Centers-Upgrade-Testing
- Leaflet v. 1.0.3
- Esri Leaflet v. 2.0.7
- Esri Leaflet Renderer v. 2.0.4
- Old version of map:  https://www.ccpa.net/2548/Senior-Community-Centers
![esri-renderers-leaflet-issue](https://cloud.githubusercontent.com/assets/12861454/25962644/806f8934-364c-11e7-8936-4472eb3e7ed8.png)

**Comment by jgravois** [comment]
not sure its the culprit, but you're not loading the same feature service in the app that works..

```js
//working
'//gis.ccpa.net/arcgiswebadaptor/rest/services/ArcGIS_Online/CountySitesData/MapServer/1'
// not working
'//gis.ccpa.net/arcgiswebadaptor/rest/services/ArcGIS_Online/SeniorCommunityCentersData/MapServer/0'

**Comment by pmacMaps** [comment]
I tested removing the renderers plugin in both examples, and it solved the problem both times. If it helps, I can create duplicate maps where the only difference is renders being in/out.

**Comment by jgravois** [comment]
i believe you.
does it make any difference if you skip specifying a custom pane in the layer constructor?

**Comment by pmacMaps** [comment]
No.  I tested not creating a custom pane and the layer still did not draw.  On a separate note, I had to create the custom pane so the popups would work.  Before adding the pane, the popup wouldn't open once I zoomed the map in.  I am thinking of an issue in Esri Leaflet, unless you're already aware of that.

**Comment by jgravois** [comment]
what about something as simple as this?

```js
var center = [40.15, -77.25];
var map = L.map('map').setView(center, 10);

var myIcon = L.icon({
  iconUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAMxJREFUOI3t0LEKglAUxvF/EQmBFPUAQUM4VBi0JQ5uQRAtvkPv0GO0OjQF7U5RY7SYQTgk5FbvIBQ0aTglXYuGvul+cO6PwynwoRSih8rAbdK+ioJnPNnB1mO4z7CqM1ZF4bW08JzQfm6cdf7wj8B3brhsCPBQ6NFCI09OHN5iM2MS9ylL2mji8Ildogccs4EbdIF53OsoL/+kgjVGAAQcaKHRQc8GLiJhYGJgphlPD7+TP/xF2GdfKSELg5fQryXgFVZ5hSUMR/nYKR7ypCcM24lKGgAAAABJRU5ErkJggg==',
});

L.marker(center, {
  icon: myIcon 
}).addTo(map);
```

**Comment by pmacMaps** [comment]
I was planning on using the L.icon as a work around.  But I still wanted to make Esri aware of this quirk.  It is quite possible our CMS is interfering with the plugin, but at least now it's documented.

**Comment by jgravois** [comment]
i didnt mean to suggest using `L.icon` as a workaround, but rather as a minimal repro case to try and help pinpoint more closely where exactly things are breaking down.

1. are you able to view the icon in your CMS?
2. if so are you still able to see if if you also display a basemap?
3. if so, are you still able to see it after you add the county outline?

my _guess_ is that the problem has to do with the `z-index` work in Leaflet 1.x to do with panes. so taking a close look at how things are stacked in the DOM would probably be a good idea.

**Comment by pmacMaps** [comment]
I'm going to test the basic map you proposed.  On a side note, I'm developing an embedded map on a Drupal 7.54 site, and I ran into the same issue where the point feature layer won't show up unless I remove the Esri Leaflet Renderers plugin.

**Comment by pmacMaps** [comment]
@jgravois I have an update:

1. I was able to test your code above, and the point appeared.  When I added a basemap to the mix (OSM), the point still showed up.
2.  Whenever I used a *geojson file as the data source, the features showed up.  This was the case with our CivicPlus CMS and the Drupal 7.54 site.

I'm not sure what the next steps are for diagnosing the issue, but I can help if need be.  Because I'd like to get my upgrades finished, I'm going to remove the Renderers plugin and symbolize my points using a L.Icon.  To me, it seems like the plugin is not playing nicely with CMSes for at least Point data (haven't tested Polygon data, and a Polyline data works).

**Comment by jgravois** [comment]
thanks for doing the additional testing.  i'll see if i can set up a drupal instance to test on my side.

**Comment by jgravois** [comment]
How exactly are you embedding your custom `<html>` and `.js` into Drupal and CivicPlus?

**Comment by pmacMaps** [comment]
**Drupal**

1. Add a **_<div="membershipMap">_** element within the page editor widget for node 8.
2. Within **_template.php_** in the ./sites/all/themes/[theme] directory:
3. within the **_[theme]_preprocess_node()_** function, call _drupal_add_css_ and _drupal_add_js_ within a _if (drupal_get_path_alias("node/8"))_ conditional statement

**CivicPlus**

Within the page editor, I add two Custom HTML widgets.  The first loads the various css and js files.  the second contains the div with the custom id for the map, and the js file(s) for the map.  I've included some screen shots:
![civicplus-customhtml-1](https://cloud.githubusercontent.com/assets/12861454/26325886/c7a02238-3f06-11e7-99f3-db9d3ff9a6d0.PNG)
![civicplus-customhtml-2](https://cloud.githubusercontent.com/assets/12861454/26325887/c7b43b24-3f06-11e7-8a32-7e45ddd1c479.PNG)

**Comment by jgravois** [comment]
thanks for humoring me @pmacMaps 

i was able to get a repo case set up locally by following the steps below
1. ran a [MAMP](https://www.drupal.org/docs/develop/local-server-setup/mac-os-development-environment/howto-create-a-local-environment) drupal installation
2. created a 'basic page'
3. allowed 'full html'
4. copied our generic renderers sample and tweaked the div height/width

(i tried using [Acquia](https://www.acquia.com/cloud-hosting/drupal-web-hosting) previously and they make it a bit tougher to pass in raw html)

i haven't figured out how to _solve_ the problem yet, but now i can see that the reason the symbols aren't displaying is because some sort of .css conflict is squashing the border and padding for each embedded image down to `0px`.

![screenshot 2017-05-26 13 01 52](https://cloud.githubusercontent.com/assets/3011734/26510923/625e038e-4214-11e7-9a83-9fdbee98103b.png)

**Comment by jgravois** [comment]
i'm still scratching my head here, but you can solve this problem by utilizing the appropriate default pane associated with point geometries

```js
L.esri.featureLayer({
  url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/DamageAssessment/MapServer/0',
  pane: 'markerPane'
}).addTo(map);
```
i'm going to propose a small change in esri leaflet to make sure that the appropriate pane is set automatically, but this still doesn't explain why both `overlayPane` and any other `custom` pane you create are squashing inline images.

**Comment by pmacMaps** [comment]
Using markerPane with the Renderers plugin resolves the issue for me.  I'm okay with closing this issue, as we've found a solution.

**Comment by jgravois** [comment]
since we still haven't gotten to the root of the problem, lets leave the issue open. 

that said, since in the next release it won't be necessary to specify the markerPane manually, and you have what you need for now, i'm happy to put it on the back burner.

**Comment by jwasilgeo** [comment]
Hi @pmacMaps! Any updates or thoughts with this oldie? 😃

**Comment by pmacMaps** [comment]
No, I just used the `panes` solution proposed by @jgravois.  We can close this, but the underlying issue, whatever it may be, might still exist.

**Comment by jwasilgeo** [comment]
Thanks for the follow up. Let's close it for now as there is quite a bit of good info in the conversation above and then reopen/revisit should anyone get back into figuring out what else was making this occur.
