### ISSUE TITLE
service symbology not honored when field names are lower-case

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#142]
user report from @jmunowitch. doesn't have a public dummy service he can share.

need to find another one to test with.

**Comment by jmunowitch** [comment]
Specifics of the usecase:
Query Layer in an ArcGIS Desktop (10.3) MXD, connected to an Oracle DB Backend 
Published to ArcGIS Server (Linux, unknown version), with data copied over to the server.

Library Versions: 
- leaflet@1.0.3
- esri-leaflet@2.0.7
- esri-leaflet-renderers@2.0.6

Visual evidence of the symbology:
![symbology](https://user-images.githubusercontent.com/1542229/36561118-a6742042-17c7-11e8-968e-4622dc812bb0.png)
Visual evidence of the AGS Service working:
![symbology2](https://user-images.githubusercontent.com/1542229/36561199-ea8efaa4-17c7-11e8-8a28-88ad0efb25aa.png)

**Comment by jgravois** [comment]
thx. if you could copy/paste a snippet to show an example of the [service metadata](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3?f=json) too, that'd be really helpful.

```json
"fields": [
    {
      "name": "OBJECTID",
      "type": "esriFieldTypeOID",
      "alias": "OBJECTID",
      "domain": null
    },
    {
      "name": "Shape",
      "type": "esriFieldTypeGeometry",
      "alias": "Shape",
      "domain": null
    },
    {
      "name": "STATE_NAME",
      "type": "esriFieldTypeString",
      "alias": "STATE_NAME",
      "length": 25,
      "domain": null
    }
]

**Comment by jmunowitch** [comment]
I have cut out a lot of fields, but included the ones I think were relevant:

```
"fields":[
    {"name":"floor","type":"esriFieldTypeString","alias":"FLOOR","length":20,"domain":null},
    {"name":"geometry","type":"esriFieldTypeGeometry","alias":"GEOMETRY","domain":null},
    {"name":"company_name","type":"esriFieldTypeString","alias":"COMPANY_NAME","length":50,"domain":null},
    {"name":"objectid","type":"esriFieldTypeOID","alias":"OBJECTID","domain":null},
    {"name":"st_area(geometry)","type":"esriFieldTypeDouble","alias":"st_area(geometry)","domain":null},
    {"name":"st_length(geometry)","type":"esriFieldTypeDouble","alias":"st_length(geometry)","domain":null}
]
```

**Comment by jmunowitch** [comment]
It looks like I was able to fix the problem on the ArcGIS Server end:
![publishags](https://user-images.githubusercontent.com/1542229/36563394-d2515610-17ce-11e8-8092-cba516259c27.png)

Publishing the service with only `Mapping` capabilities publishes the attributes with all caps (like the layer in ArcGIS Desktop). I originally had `KML` and `Feature Access` enabled as well, which caused the layer to be published with lower case attribute names, which messed up the symbology, as well as some of my esri-leaflet code.

Not retaining the symbology for the service still seems like a bug though.

**Comment by jgravois** [comment]
>  I originally had KML and Feature Access enabled as well, which caused the layer to be published with lower case attribute names.

thats _really_ weird.

glad to hear its just a curiosity at this point, but i'll still find time to try and trap the undesirable behavior here.

**Comment by jmunowitch** [comment]
My guess is AGS does this for compatibility sake for KML or Feature Access. Maybe capitalization isn't supported in one of those standards?

**Comment by jgravois** [comment]
PRs welcome, I don't have plans to work on this one though.
