### ISSUE TITLE
Default Marker show up after clustering with esri-leaflet-cluster

### ISSUE THREAD

**Issue by zubairkhanafridi** [Esri/esri-leaflet-renderers#143]
I am using esri-leaflet-cluster plugin to load a cluster feature layer. The feature layer has many icons which are I am trying to render using the esri-leaflet-renderers plugin. 
When using the esri-leaflet-renderers alone, the icons are rendered as required. When I try to use it with the cluster feature layer, I get the default blue icon markers instead of the icons defined in the map service.

Could you let me know what might be the issue and how I can use both the plugins together.

**Comment by jgravois** [comment]
duplicate of https://github.com/Esri/esri-leaflet-cluster/issues/18
