### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by francharbo** [Esri/esri-leaflet-renderers#155]
Hello,

I would like to know when will be the release to manage clusterLayer ?
I already saw that some code were done regarding this.

**Comment by gavinr** [comment]
@francharbo to which code are you referring?

**Comment by jgravois** [comment]
I _think_ they're referring to #102

I didn't know about that thread when we discussed the issue later in https://github.com/Esri/esri-leaflet-cluster#18

**Comment by francharbo** [comment]
I saw this commit while browsing your files
[https://github.com/Esri/esri-leaflet-renderers/commit/b1679eb3ad2d0164fc1250c390642ed99b919475](https://github.com/Esri/esri-leaflet-renderers/commit/b1679eb3ad2d0164fc1250c390642ed99b919475)

Which is making available for clusterLayer the renderers

**Comment by jgravois** [comment]
wow. i forgot all about #144 

@gavinr you could release that _as is_, but it'd be ideal if you could tackle #152 first.

**Comment by gavinr** [comment]
Released - https://github.com/Esri/esri-leaflet-renderers/releases/tag/v2.1.1
