### ISSUE TITLE
initHooks are not setted using import style

### ISSUE THREAD

**Issue by francharbo** [Esri/esri-leaflet-renderers#159]
Hello,

I tried using the version 2.1.1 of esri-leaflet-renderers with esri-leaflet-cluster and I am encountering some problems using import style.

You can find attached a running sample (simply open index.html with a live server)

You'll see that it seems to be working, but if you look into L.esri.Cluster.FeatureLayer.__super__._initHooks, you'll see that it's empty...

If I use version 2.1.0, it is working properly.

[renderers-bug.zip](https://github.com/Esri/esri-leaflet-renderers/files/4830096/renderers-bug.zip)

Thank you for your help

**Comment by francharbo** [comment]
After looking a bit into it, I saw that the initHooks should be in `L.esri.Cluster.FeatureLayer.prototype`
So my minimal example is working just fine...
But it's not working in my project :'(

**Comment by francharbo** [comment]
Solved with #160

**Comment by jgravois** [comment]
thanks for identifying the fix for this @francharbo!
