### ISSUE TITLE
Support for esri leaflet 3

### ISSUE THREAD

**Issue by fgoulet** [Esri/esri-leaflet-renderers#176]
I did npm install with --legacy-peer-deps to get it installed along "esri-leaflet": "^3.0.8", but it does not seems to work.

**Comment by gavinr** [comment]
Hi, could you please post a replication case (using JSBin or some similar process) to show the issue?

**Comment by lielvan** [comment]
Chiming in since I also ran into this issue:
Expected: 
run `npm install esri-leaflet esri-leaflet-renderers`, expecting esri-leaflet ^3.x.
Actual:
```

**Comment by pmacMaps** [comment]
The issue I have (and I believe others have) is it isn't clear how to import Esri Leaflet Renderers in a project that uses ES modules and a bundler, and get the server-rendered symbology applied.  When you add the various Esri Leaflet libraries as separate script tags, it works.  But many of use want to use bundlers.

**Comment by gavinr** [comment]
Thank you all for the input. Seems like the original issue is summarized (by the past two comments) around "we need example code to show how to use ES modules with bundlers". I have two examples here:

- https://github.com/gavinr/esri-leaflet-react-demo
- https://github.com/gavinr/esri-leaflet-svelte-demo

But I think we need more than just those samples - probably a tutorial or documentation page on it.

## Second issue
Specifically to esri-leaflet-renderers, there's an issue with the dependencies that @lielvan is pointing out. The solution is to make a change in this repo similar to what we did in esri-leaflet-geocoder: https://github.com/Esri/esri-leaflet-geocoder/pull/275/

**Comment by gavinr** [comment]
This is fixed in v3.0.0. 

We will also add more documentation for ES modules in the future.

Thanks!
