### ISSUE TITLE
create first tagged release

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#20]
it'd be beneficial to:
1. update the package.json with a version number (perhaps `v0.0.1-alpha.1` to match convention of geocoder?)
2. create a tagged release.
3. create a changelog indicating the minimum esri leaflet version necessary for compatibility.
4. update the package.json again (`v0.0.1-alpha.2`)

**Comment by kneemer** [comment]
Working on this now but am going to use beta instead of alpha as it feels closer to a beta release.  I'm going to push the branch I'm working on upstream so you can make any changes to it before we merge it to master, create a release, update the package.json and remove the dist files.

**Comment by kneemer** [comment]
I pushed up the branch prepare-to-release and it already has the tag.  I hope that isn't a problem when merging back to master.  I'm new to the tagging/release strategy.  Feel free to decline the pull request if anything looks amiss.

**Comment by jgravois** [comment]
since pushing out the release creates a tag as well, we need to remove the previous one [here](https://github.com/Esri/esri-leaflet-renderers/tags).

safe to close after thats done and #22 is merged.

**Comment by jgravois** [comment]
yay! #23
