### ISSUE TITLE
Building from source files fails

### ISSUE THREAD

**Issue by bviswanathan** [Esri/esri-leaflet-renderers#24]
Steps to repro:

* Fork and Clone the repo.
* `npm install` to install the dependencies
* Run `grunt`
* It will fail in `karma` task with the below error:
![image](https://cloud.githubusercontent.com/assets/6334277/6311760/ad263036-b91c-11e4-8d5c-a36fb413a4fc.png)

**Comment by jgravois** [comment]
to fix the problem immediately, you could dig into the node_modules folder and delete 'chai' then run 
```
npm install chai@1.10.0
```

in the future i think @kneemer and i are leaning toward updating the syntax of the tests (as opposed to locking the version of the dependency).

thanks for reporting!

**Comment by jgravois** [comment]
fixed by #25

**Comment by bviswanathan** [comment]
Thanks @jgravois and @kneemer
