### ISSUE TITLE
icons for authenticated layers not using token

### ISSUE THREAD

**Issue by kneemer** [Esri/esri-leaflet-renderers#49]
@bviswanathan reported this issue.  Authenticated layers with icons need to pass the token in at https://github.com/esri/esri-leaflet-renderers/blob/master/src/Symbols/PointSymbol.js#L12

**Comment by jgravois** [comment]
are you up for trying to submit a PR with the fix @bviswanathan?

**Comment by bviswanathan** [comment]
Thanks @kneemer @jgravois for creating an issue. Yes, I will fix it and send a PR

**Comment by kneemer** [comment]
@bviswanathan Just wanted to let you know that the options used in the PointSymbol are created at https://github.com/Esri/esri-leaflet-renderers/blob/master/src/FeatureLayerHook.js#L151 This is probably where you would want to add the token if it is available to make it accessible by the PointSymbol class.

**Comment by bviswanathan** [comment]
Yes, just saw that. Will add a `token` property to `options` that we can use it in `PointSymbol.js`
