### ISSUE TITLE
sample that shows how to manipulate styles defined in the service

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#53]
once we have a dependable hook (see: https://github.com/Esri/esri-leaflet/issues/545) lets write a sample that shows how to make a simple modification (like setting opacity) to symbology defined by the service itself.

**Comment by jgravois** [comment]
```javascript
FeatureLayer.eachFeature(function(feature){
  feature.options.fillOpacity = 0.5;
  feature.setStyle(feature.options);
});
```

**Comment by jgravois** [comment]
ready to be tackled (via c38e0860e120880249000dadd56c1853b1e60854)

**Comment by jgravois** [comment]
would be even cooler if we could mixin style options provided in the feature layer constructor

**Comment by kneemer** [comment]
@jgravois, the only style samples I see are to define either the style() or pointToLayer() functions.  Can you provide a sample of passing in style options as an object to a feature layer constructor?

**Comment by jgravois** [comment]
i hadn't really given it any thought, but i guess the way i see this working is that we continue to use the existing `style()` and `pointToLayer()` functions and then mixin whats provided with what's defined by the server itself (if that makes any sense)?

**Comment by kneemer** [comment]
Hmm, so run the user defined function then run the renderer function and apply any attributes that were not defined by the user?

**Comment by jgravois** [comment]
sounds less elegant when you explain it in terms of what we'll actually have to do :smile:

**Comment by kneemer** [comment]
It would be elegant from the user perspective :)
