### ISSUE TITLE
doc lack of support for unique value renderers based on multiple fields

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#55]
we need to add a note in the documentation that unique value renderers based on more than one attribute field [aren't](https://github.com/Esri/esri-leaflet-renderers/blob/master/src/Renderers/UniqueValueRenderer.js#L7) supported.

**Comment by kneemer** [comment]
I wanted to support multiple fields but the lack of documentation on how they behave stopped me. If you have a reference other than http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r30000019t000000 that explains them a little more thoroughly I would appreciate it.
