### ISSUE TITLE
Receive 302 when accessing secured services

### ISSUE THREAD

**Issue by bradj** [Esri/esri-leaflet-renderers#59]

**Comment by jgravois** [comment]
i encountered errors displaying features in versions of esri-leaflet newer than [rc.4](http://cdn-geoweb.s3.amazonaws.com/esri-leaflet/1.0.0-rc.5/esri-leaflet-src.js) when supplying a hardcoded `token` in my L.esri.FeatureLayer constructor, but everything seems to be working appropriately (including in this plugin) when i rolled back.  

if you aren't seeing the same thing, it'd be really helpful if you could provide some additional information.

1. are you testing a tagged release of esri leaflet renderers or are you pointing at `master`?
2. is your feature service hosted in ArcGIS Online or ArcGIS Server? if ArcGIS Server, what version and authentication type?
3 what is the feature layer geometry type, renderer and symbol?
4. if you aren't authenticating using `token` in the `L.esri.FeatureLayer` constuctor, how exactly are you going about it?

**Comment by bradj** [comment]
I am using latest which currently is v1.0.0-rc.8.  I switched to rc.3 to see if that fixed my issue but it hasn't.

1. I am using this version for the renderer //cdn-geoweb.s3.amazonaws.com/esri-leaflet-renderers/0.0.1-beta.3/esri-leaflet-renderers.js
2. I am on 10.22 and using token based auth
3. Point, Unique Value Renderer, and esriPMS
4. I am following this pattern http://esri.github.io/esri-leaflet/examples/arcgis-server-auth.html

I can see the requests in dev tools returning a 302. When I try to browse to the generated url I get the ArcGIS Server REST API Login page. If I login through that page then the images will show up until the token expires, at which point I will start getting 302's again.

I am correctly retrieving and supplying a token with the L.esri.featureLayer object which is verified by the proper geometry being returned. esri-leaflet-renderer does not appear to honor said token and tries to make it's own way.

**Comment by jgravois** [comment]
thanks @bradj.  i have a hunch the behavior is specific to picture marker symbols.  we'll take a look.

**Comment by kneemer** [comment]
@jgravois I think you're hunch is correct.  We should probably do another release that includes the fix for issue #50  and see if it resolves the problem.  @bradj I'm not sure if you have tried building from master yet but if you are comfortable with doing so and it fixes the problem that would help us verify before release.

**Comment by bradj** [comment]
@kneemer, master appears to have the special sauce! I am seeing the images on my map and the URL now has the token included in the params.

I verified by navigating to the services directory to make sure the login page still showed up and that the browser didn't have a session lying around, both checked out.

**Comment by jgravois** [comment]
closing.  thanks for bringing the issue in esri leaflet with secure services to our attention @bradj!

**Comment by patrickarlt** [comment]
We are in the process of getting the larger issue fixed too! https://github.com/Esri/esri-leaflet/issues/565
