### ISSUE TITLE
add support for unique value renderers based on more than one field

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#60]
in general, multi-field unique value renderers just allow the service to define different permutations of unique combinations of the attributes associated with a particular feature in two (or three) fields as opposed to just looking at one.  the choice of delimiter used to separate individual values is configurable.

for example a feature like this:
```json
{
  "geometry": {},
  "properties": {
    "name": "somestring",
    "type": "cool"
  }
}
```
with the default field delimiter `,` would be appropriately symbolized in a renderer expressed as:
```json
"type": "uniqueValue",
"field1": "name",
"field2": "type",
"field3": null,
"fieldDelimiter": ",",
"uniqueValueInfos": [{
  "symbol": { ... },
  "value": "somestring,cool"
}]
```
i'm not sure if/where documentation on this exists, but i'm pretty comfortable with the pattern so i'd be **more** than happy to chat about it in more depth to provide more clarification if it'd be helpful.

**Comment by kneemer** [comment]
We should do that when time permits.
