### ISSUE TITLE
1.0.0 / 2.0.0 release steps

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#76]
to do (in order)
- [x] test/merge support for unique value renderers based on more than one field
- [x] tag 1.0.0
- [x] PR to jsdelivr
- [x] refactor Leaflet.ShapeMarkers
- [x] merge #72
- [x] merge 2.0.0 into master?
- [ ] tag 2.0.0-beta.1
- [ ] hook up travis continuous testing

**Comment by jgravois** [comment]
almost done. i can update the changelog.  is there anything else we need to do before tagging?

i'm partial to just skipping the betas altogether and releasing 2.0.0.  how do you feel about that?

**Comment by kneemer** [comment]
Let me get rid of my npm link for leaflet-shape-markers and test with the release.

**Comment by kneemer** [comment]
Looks good with a fresh clone, and independent npm install and downloading zip file from release.

**Comment by jgravois** [comment]
awesome!  can you try and hook up Travis now?
