### ISSUE TITLE
Demo comparison app: could the Esri JSAPI map make use of custom navigation animations?

### ISSUE THREAD

**Issue by jwasil** [Esri/esri-leaflet-renderers#90]
Question/enhancement request:

First of all, _awesome_ work all around with Esri/esri-leaflet and Esri/esri-leaflet-renderers.  Regarding the [comparison app](http://esri.github.io/esri-leaflet-renderers/spec/comparisons.html), I was wondering if the JSAPI map could incorporate custom pan and zoom duration/rates, as in [this JSAPI sample](https://developers.arcgis.com/javascript/jssamples/mapconfig_smoothpan.html).  I've found that something roughly approximate to the following values gives the Esri map similar pan and zoom speeds as the Leaflet map.

```javascript
esriConfig.defaults.map.panDuration = 250;
esriConfig.defaults.map.panRate = 1;
esriConfig.defaults.map.zoomDuration = 250;
esriConfig.defaults.map.zoomRate = 1;
```

Thoughts?

**Comment by jgravois** [comment]
thanks for sharing the idea!

just my two cents, but i always thought it was kind of cool to see all the idiosyncratic differences in the default behavior of the APIs that don't have anything to do with renderers...

that being said, i was playing around with simplifyFactor settings in the esri-leaflet FeatureLayer constructor to try and speed up our rendering of the freeways. :smile:

**Comment by jwasil** [comment]
@jgravois nice, regarding the simplifyFactor; that'll be cool to see.

Well, the zoomDuration and the other esriConfig properties were just a thought for the sake of some nit-picky discussion.  I agree that it's also interesting to see the default settings and flavors that each mapping lib employs.  Y'all feel free to do whatever you like with this issue, including closing it right away!

**Comment by jgravois** [comment]
i think i'm going to leave the comparison sample *bone stock*, but keep the suggestions coming!

**Comment by jwasil** [comment]
:+1:
