### ISSUE TITLE
API + Usage Doc

### ISSUE THREAD

**Issue by andygup** [Esri/esri-leaflet-renderers#94]
Love the concept. Please add docs. Currently lots of code deciphering is needed to figure it out.

**Comment by jgravois** [comment]
i'm not sure i understand what's to doc.
the plugin doesn't contain any classes, methods or properties.  it simply extends L.esri.featureLayer to automatically take on the renderer defined in the service itself.

**Comment by andygup** [comment]
@jgravois I'm suggesting exactly what you said should be spelled out, along with which renderers are supported. I didn't get it until I looked thru the code. 

My expectation was something like the [JS API ClassBreaksRenderer](https://developers.arcgis.com/javascript/jsapi/classbreaksrenderer-amd.html)  but what I got was [this](https://github.com/Esri/esri-leaflet-renderers/blob/master/src/Renderers/ClassBreaksRenderer.js).

**Comment by jgravois** [comment]
i see what you're saying.

the limitations are clearly spelled out in the [readme](https://github.com/Esri/esri-leaflet-renderers/blob/master/README.md#limitations), but i'll add a little more info to clarify the behavior of the plugin.

there's not somewhere else you were expecting to find doc, is there?

**Comment by andygup** [comment]
Nope, I wasn't expecting doc elsewhere. A little more info on the behavior will be great, thanks.

**Comment by jgravois** [comment]
cool.  thanks for taking the time to articulate your confusion.  i'm **sure** you aren't the only one who felt that way.

you can find my readme tweaks in #95

**Comment by andygup** [comment]
Awesome, I think that tweak covers it!
